# Generated by Django 5.0.3 on 2024-06-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='registration',
            new_name='registrationType',
        ),
        migrations.AddField(
            model_name='applicant',
            name='period',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
